### ISSUE TITLE
404 Error retrieving met temperature and precipitation data.

### ISSUE THREAD

**Issue by RRTogunov** [gjearevoll/BioDivMapping#112]
errors:
Error in download.file(focalURL, destfile = file_path) : 
  cannot open URL 'https://thredds.met.no/thredds/fileServer/KSS/Gridded_climate_normals_1991-2020/precipitation/rr_normal_jja_1991-2020.nc'
  
Error in download.file(focalURL, destfile = file_path) : 
  cannot open URL 'https://thredds.met.no/thredds/fileServer/KSS/Gridded_climate_normals_1991-2020/temperature/tm_normal_jja_1991-2020.nc'
  
These paths do not exist. I can browse up to https://thredds.met.no/thredds/, but there is no "fileServer" in that directory. No idea what the issue might be.

**Comment by samaperrin** [comment]
I don't know what's causing this either. May be that we need to instead use the same tactic as for the corine data, ie. "you don't have this file saved locally here's where to download it". That work for you?

**Comment by samaperrin** [comment]
Closed - was a matter of adding "wb" as an argument to download.file function
