### ISSUE TITLE
Resolution of environmental rasters too high

### ISSUE THREAD

**Issue by samaperrin** [gjearevoll/BioDivMapping#58]
Currently in the environmentalImport.R script we project all our environmental raster layers onto the one with the highest resolution. This takes up a lot of unnecessary space, particularly since worldclim reosolution is so damn high. Would be better to get it onto a resolution of 100.

**Comment by RRTogunov** [comment]
I think it makes sense to specify desired resolution and projection up front, but if I'm not wrong, I think worldclim that we are using is about 400 m resolution.

**Comment by samaperrin** [comment]
This was solved in [this pull request](https://github.com/gjearevoll/BioDivMapping/pull/59)
