### ISSUE TITLE
specify predictionDim of sdmWorkflow in masterScript.R

### ISSUE THREAD

**Issue by RRTogunov** [gjearevoll/BioDivMapping#69]
users currently separately define "res" for download/processing of environmental data and 'predictionDim' for model prediction; should these be the same parameter?
eg. either  predictionDim in sdmWorkflow should use 'res' from the masterScript.R, or the desired prediction resolution (eg c(300,400)) be the target resolution for all environmental data?
regardless, this parameter should also be moved to masterScript.R.

_Originally posted by @RRTogunov in https://github.com/gjearevoll/BioDivMapping/pull/68#discussion_r1400263401_

**Comment by samaperrin** [comment]
Since Phil has created a prediction projection based on a given resolution, we can create this projection using the 'res' variable defined early on in the master Script.

**Comment by RRTogunov** [comment]
I think this is closed, yeah?

**Comment by samaperrin** [comment]
Yep, linking it to the correct PR now
