### ISSUE TITLE
Turn abundance back into presence-absence

### ISSUE THREAD

**Issue by samaperrin** [gjearevoll/BioDivMapping#91]
While we initially used the Nina Insect Monitoring Dataset as an abundance dataset to test that the model could take count data, our models currently have a poor understanding of abundance data. Until the modellers have had time to put a bit more thought into this, we should keep this data as presence-absence.

**Comment by oharar** [comment]
I'd keep it as abundance in the model, but in the interpretation we can stick to presence.

If you have an overdispersion term in the model, it'll be fine.
